In [7]:
import psycopg2
import pandas as pd
import os
import numpy as np 
from sqlalchemy import create_engine

# 1. Чтение данных из разных источников

In [36]:
# Настройки подключения к базе данных
DB_CONFIG = {
    "dbname": "postgres",
    "user": "postgres",
    "password": "3421",
    "host": "localhost",
    "port": 5433
}

# Подключение к базе данных
try:
    conn = psycopg2.connect(**DB_CONFIG)
    print("Подключение установлено")
except Exception as e:
    print(f"Ошибка подключения: {e}")

# Получение нужной таблицы
try:
    query = "SELECT * FROM public.client_inquiries;"
    data= pd.read_sql_query(query, conn)
    print("client_inquiries:")
    print(data)
except Exception as e:
    print(f"Ошибка выполнения запроса: {e}")

# Закрытие подключения
finally:
    if conn:
        conn.close()
        print("Подключение закрыто")

Подключение установлено
client_inquiries:
     id  client_id inquiry_date                     issue       status
0   301       1000   2025-02-09            Возврат товара          new
1   302       1001   2025-02-08           Вопрос по акции       closed
2   303       1002   2025-03-01        Вопрос по гарантии      pending
3   304       1003   2025-03-02      Проблема с аккаунтом  in_progress
4   305       1004   2025-02-08  Консультация по продукту          new
..  ...        ...          ...                       ...          ...
95  396       1095   2025-02-16        Вопрос по доставке       closed
96  397       1096   2025-02-10           Ошибка в заказе  in_progress
97  398       1097   2025-02-10           Вопрос по акции  in_progress
98  399       1098   2025-02-18        Вопрос по гарантии  in_progress
99  400       1099   2025-02-08        Вопрос по гарантии       closed

[100 rows x 5 columns]
Подключение закрыто

C:\Users\User\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [38]:
df_postgres = pd.DataFrame(data)
df_postgres

     id  client_id inquiry_date                     issue       status
0   301       1000   2025-02-09            Возврат товара          new
1   302       1001   2025-02-08           Вопрос по акции       closed
2   303       1002   2025-03-01        Вопрос по гарантии      pending
3   304       1003   2025-03-02      Проблема с аккаунтом  in_progress
4   305       1004   2025-02-08  Консультация по продукту          new
..  ...        ...          ...                       ...          ...
95  396       1095   2025-02-16        Вопрос по доставке       closed
96  397       1096   2025-02-10           Ошибка в заказе  in_progress
97  398       1097   2025-02-10           Вопрос по акции  in_progress
98  399       1098   2025-02-18        Вопрос по гарантии  in_progress
99  400       1099   2025-02-08        Вопрос по гарантии       closed

[100 rows x 5 columns]

In [8]:
  # Чтение из CSV
df_csv = pd.read_csv('C:/Users/User/Downloads/support_quality_ratings.csv', sep = ',')
df_csv

,rating_id,inquiry_id,client_id,agent_id,rating_date,overall_rating,resolution_speed_rating,politeness_rating,knowledge_rating,feedback,would_recommend,regulation_followed
0,1,47,1028,9,2025-02-15,2,2,3,2,Разочарован сервисом,False,True
1,2,17,1050,2,2025-01-27,4,5,4,3,Все объяснили понятно и доступно,True,True
2,3,78,1024,9,2024-10-29,4,3,3,5,"Отличный сервис, быстрое решение проблемы",True,True
3,4,61,1020,4,2024-12-25,4,5,3,4,Всегда приятно иметь дело с профессионалами,True,True
4,5,21,1022,7,2024-09-23,5,5,5,5,Вежливый и компетентный специалист,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,4,1049,8,2024-10-20,3,2,4,2,"Решили проблему, но долго",False,True
96,97,40,1035,6,2024-09-24,5,5,5,5,"Отличная работа, спасибо!",True,True
97,98,57,1041,8,2024-11-23,2,3,1,1,Очень долго решали проблему,False,True
98,99,83,1020,2,2025-02-08,5,5,4,5,Оперативно решили мою проблему,True,True
99,100,43,1025,9,2024-09-24,5,5,5,4,Оперативно решили мою проблему,True,True

In [9]:
 # Чтение из Excel
df_excel = pd.read_excel("C:/Users/User/Downloads/service_regulations.xlsx")
df_excel

,regulation_id,title,department,sla_target,created_date,last_updated,is_active
0,1,Обработка входящих звонков,Отдел продаж,91%,2024-02-28,2025-02-13,False
1,2,Эскалация проблем,Отдел продаж,95%,2023-09-26,2025-02-12,True
2,3,Техническая поддержка первого уровня,Отдел маркетинга,91%,2024-07-28,2025-03-06,True
3,4,Регламент доступа к системе - Специальный,Техническая поддержка,95%,2024-03-09,2024-12-11,False
4,5,Обслуживание VIP-клиентов - Временный,Отдел качества,92%,2024-07-16,2024-12-13,True
...,...,...,...,...,...,...,...
95,96,Регламент резервного копирования - Базовый,Отдел качества,93%,2023-10-03,2024-11-20,False
96,97,Процедура отчетности,Отдел тестирования,99%,2023-11-28,2025-01-12,False
97,98,Процедура обучения новых сотрудников,Отдел маркетинга,91%,2024-04-29,2024-11-07,True
98,99,Регламент документирования,Финансовый отдел,97%,2024-02-01,2025-01-22,True
99,100,Работа с критическими инцидентами,Отдел тестирования,96%,2024-03-31,2024-09-20,True

# 2. Очистка данных

In [10]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rating_id                100 non-null    int64
 1   inquiry_id               100 non-null    int64
 2   client_id                100 non-null    int64
 3   agent_id                 100 non-null    int64
 4   rating_date              100 non-null    object
 5   overall_rating           100 non-null    int64
 6   resolution_speed_rating  100 non-null    int64
 7   politeness_rating        100 non-null    int64
 8   knowledge_rating         100 non-null    int64
 9   feedback                 100 non-null    object
 10  would_recommend          100 non-null    bool
 11  regulation_followed      100 non-null    bool
dtypes: bool(2), int64(8), object(2)
memory usage: 8.1+ KB

In [16]:
# Удаление дубликатов 
df_csv = df_csv.drop_duplicates()

In [17]:
#проверка на наличие нулевых значений
df_csv.isna().sum().sum()/len(df_csv)

0.0

In [18]:
# Приведение типов данных 
df_csv['rating_date'] = pd.to_datetime(df_csv['rating_date'])

In [19]:
# Замена True на 1 и False на 0
df_csv['would_recommend'] = df_csv['would_recommend'].replace({True: 1, False: 0})
df_csv['regulation_followed'] = df_csv['regulation_followed'].replace({True: 1, False: 0})

In [20]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rating_id                100 non-null    int64
 1   inquiry_id               100 non-null    int64
 2   client_id                100 non-null    int64
 3   agent_id                 100 non-null    int64
 4   rating_date              100 non-null    datetime64[ns]
 5   overall_rating           100 non-null    int64
 6   resolution_speed_rating  100 non-null    int64
 7   politeness_rating        100 non-null    int64
 8   knowledge_rating         100 non-null    int64
 9   feedback                 100 non-null    object
 10  would_recommend          100 non-null    int64
 11  regulation_followed      100 non-null    int64
dtypes: datetime64[ns](1), int64(10), object(1)
memory usage: 10.2+ KB

In [12]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   regulation_id  100 non-null    int64
 1   title          100 non-null    object
 2   department     100 non-null    object
 3   sla_target     100 non-null    object
 4   created_date   100 non-null    object
 5   last_updated   100 non-null    object
 6   is_active      100 non-null    bool
dtypes: bool(1), int64(1), object(5)
memory usage: 4.9+ KB

In [23]:
# Удаление дубликатов 
df_excel = df_excel.drop_duplicates()

In [24]:
#проверка на наличие нулевых значений
df_excel.isna().sum().sum()/len(df_excel)

0.0

In [25]:
# Приведение типов данных 
df_excel['created_date'] = pd.to_datetime(df_excel['created_date'])
df_excel['last_updated'] = pd.to_datetime(df_excel['last_updated'])

In [26]:
# Замена True на 1 и False на 0
df_excel['is_active'] = df_excel['is_active'].replace({True: 1, False: 0})

In [30]:
#Удаление посторонних символов (%)
df_excel['sla_target']=df_excel['sla_target'].str.replace(r"%","")

In [31]:
#изменение типа данных
df_excel['sla_target']=df_excel['sla_target'].astype('int64')

In [33]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   regulation_id  100 non-null    int64
 1   title          100 non-null    object
 2   department     100 non-null    object
 3   sla_target     100 non-null    int64
 4   created_date   100 non-null    datetime64[ns]
 5   last_updated   100 non-null    datetime64[ns]
 6   is_active      100 non-null    int64
dtypes: datetime64[ns](2), int64(3), object(2)
memory usage: 6.2+ KB

In [14]:
df_postgres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            100 non-null    int64
 1   client_id     100 non-null    int64
 2   inquiry_date  100 non-null    object
 3   issue         100 non-null    object
 4   status        100 non-null    object
dtypes: int64(2), object(3)
memory usage: 4.0+ KB

In [34]:
# Удаление дубликатов 
df_postgres = df_postgres.drop_duplicates()

In [42]:
# Приведение типов данных 
df_postgres['inquiry_date'] = pd.to_datetime(df_postgres['inquiry_date'])

In [40]:
df_postgres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            100 non-null    int64
 1   client_id     100 non-null    int64
 2   inquiry_date  100 non-null    datetime64[ns]
 3   issue         100 non-null    object
 4   status        100 non-null    object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 4.0+ KB

# 3. Согласование данных

In [47]:
df_csv.rename(columns={'rating_id':'id'}, inplace=True)
df_csv.head(3)

,id,inquiry_id,client_id,agent_id,rating_date,overall_rating,resolution_speed_rating,politeness_rating,knowledge_rating,feedback,would_recommend,regulation_followed
0,1,47,1028,9,2025-02-15,2,2,3,2,Разочарован сервисом,0,1
1,2,17,1050,2,2025-01-27,4,5,4,3,Все объяснили понятно и доступно,1,1
2,3,78,1024,9,2024-10-29,4,3,3,5,"Отличный сервис, быстрое решение проблемы",1,1

In [48]:
df_excel.rename(columns={'regulation_id':'id'}, inplace=True)
df_excel.head(3)

,id,title,department,sla_target,created_date,last_updated,is_active
0,1,Обработка входящих звонков,Отдел продаж,91,2024-02-28,2025-02-13,0
1,2,Эскалация проблем,Отдел продаж,95,2023-09-26,2025-02-12,1
2,3,Техническая поддержка первого уровня,Отдел маркетинга,91,2024-07-28,2025-03-06,1

# 4. Объединение данных

In [62]:
# Объединение DataFrame по горизонтали
merge = pd.concat([df_csv, df_excel, df_postgres], axis=1)

print(merge)

     id  inquiry_id client_id  agent_id rating_date  overall_rating  \
0     1          47      1028         9  2025-02-15               2
1     2          17      1050         2  2025-01-27               4
2     3          78      1024         9  2024-10-29               4
3     4          61      1020         4  2024-12-25               4
4     5          21      1022         7  2024-09-23               5
..  ...         ...       ...       ...         ...             ...
95   96           4      1049         8  2024-10-20               3
96   97          40      1035         6  2024-09-24               5
97   98          57      1041         8  2024-11-23               2
98   99          83      1020         2  2025-02-08               5
99  100          43      1025         9  2024-09-24               5

    resolution_speed_rating  politeness_rating  knowledge_rating  \
0                         2                  3                 2
1                         5                  4                 3
2                         3                  3                 5
3                         5                  3                 4
4                         5                  5                 5
..                      ...                ...               ...
95                        2                  4                 2
96                        5                  5                 5
97                        3                  1                 1
98                        5                  4                 5
99                        5                  5                 4

                                       feedback  ...             department  \
0                          Разочарован сервисом  ...           Отдел продаж
1              Все объяснили понятно и доступно  ...           Отдел продаж
2     Отличный сервис, быстрое решение проблемы  ...       Отдел маркетинга
3   Всегда приятно иметь дело с профессионалами  ...  Техническая поддержка
4            Вежливый и компетентный специалист  ...         Отдел качества
..                                          ...  ...                    ...
95                    Решили проблему, но долго  ...         Отдел качества
96                    Отличная работа, спасибо!  ...     Отдел тестирования
97                  Очень долго решали проблему  ...       Отдел маркетинга
98               Оперативно решили мою проблему  ...       Финансовый отдел
99               Оперативно решили мою проблему  ...     Отдел тестирования

    sla_target  created_date last_updated is_active   id client_id  \
0           91    2024-02-28   2025-02-13         0  301      1000
1           95    2023-09-26   2025-02-12         1  302      1001
2           91    2024-07-28   2025-03-06         1  303      1002
3           95    2024-03-09   2024-12-11         0  304      1003
4           92    2024-07-16   2024-12-13         1  305      1004
..         ...           ...          ...       ...  ...       ...
95          93    2023-10-03   2024-11-20         0  396      1095
96          99    2023-11-28   2025-01-12         0  397      1096
97          91    2024-04-29   2024-11-07         1  398      1097
98          97    2024-02-01   2025-01-22         1  399      1098
99          96    2024-03-31   2024-09-20         1  400      1099

   inquiry_date                     issue       status
0    2025-02-09            Возврат товара          new
1    2025-02-08           Вопрос по акции       closed
2    2025-03-01        Вопрос по гарантии      pending
3    2025-03-02      Проблема с аккаунтом  in_progress
4    2025-02-08  Консультация по продукту          new
..          ...                       ...          ...
95   2025-02-16        Вопрос по доставке       closed
96   2025-02-10           Ошибка в заказе  in_progress
97   2025-02-10           Вопрос по акции  in_progress
98   2025-02-18        Вопрос по гарантии  in_progress
99   2025-02-08        Вопрос по гарантии       closed

[100 rows x 24 columns]

In [63]:
merge_result = pd.DataFrame(merge)
merge_result

,id,inquiry_id,client_id,agent_id,rating_date,overall_rating,resolution_speed_rating,politeness_rating,knowledge_rating,feedback,...,department,sla_target,created_date,last_updated,is_active,id,client_id,inquiry_date,issue,status
0,1,47,1028,9,2025-02-15,2,2,3,2,Разочарован сервисом,...,Отдел продаж,91,2024-02-28,2025-02-13,0,301,1000,2025-02-09,Возврат товара,new
1,2,17,1050,2,2025-01-27,4,5,4,3,Все объяснили понятно и доступно,...,Отдел продаж,95,2023-09-26,2025-02-12,1,302,1001,2025-02-08,Вопрос по акции,closed
2,3,78,1024,9,2024-10-29,4,3,3,5,"Отличный сервис, быстрое решение проблемы",...,Отдел маркетинга,91,2024-07-28,2025-03-06,1,303,1002,2025-03-01,Вопрос по гарантии,pending
3,4,61,1020,4,2024-12-25,4,5,3,4,Всегда приятно иметь дело с профессионалами,...,Техническая поддержка,95,2024-03-09,2024-12-11,0,304,1003,2025-03-02,Проблема с аккаунтом,in_progress
4,5,21,1022,7,2024-09-23,5,5,5,5,Вежливый и компетентный специалист,...,Отдел качества,92,2024-07-16,2024-12-13,1,305,1004,2025-02-08,Консультация по продукту,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,4,1049,8,2024-10-20,3,2,4,2,"Решили проблему, но долго",...,Отдел качества,93,2023-10-03,2024-11-20,0,396,1095,2025-02-16,Вопрос по доставке,closed
96,97,40,1035,6,2024-09-24,5,5,5,5,"Отличная работа, спасибо!",...,Отдел тестирования,99,2023-11-28,2025-01-12,0,397,1096,2025-02-10,Ошибка в заказе,in_progress
97,98,57,1041,8,2024-11-23,2,3,1,1,Очень долго решали проблему,...,Отдел маркетинга,91,2024-04-29,2024-11-07,1,398,1097,2025-02-10,Вопрос по акции,in_progress
98,99,83,1020,2,2025-02-08,5,5,4,5,Оперативно решили мою проблему,...,Финансовый отдел,97,2024-02-01,2025-01-22,1,399,1098,2025-02-18,Вопрос по гарантии,in_progress
99,100,43,1025,9,2024-09-24,5,5,5,4,Оперативно решили мою проблему,...,Отдел тестирования,96,2024-03-31,2024-09-20,1,400,1099,2025-02-08,Вопрос по гарантии,closed

# 5. Сохранение результатов

In [66]:
# Настройки подключения к базе данных
DB_CONFIG = {
    "dbname": "postgres",
    "user": "postgres",
    "password": "3421",
    "host": "localhost",
    "port": 5433
}

# Создание строки подключения
connection_string = f"postgresql+psycopg2://{DB_CONFIG['user']}:{DB_CONFIG['password']}@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['dbname']}"

# Подключение к базе данных
try:
    engine = create_engine(connection_string)
    conn = engine.connect()
    print("Подключение установлено")
except Exception as e:
    print(f"Ошибка подключения: {e}")

# Загрузка нужной таблицы
try:
    merge_result.to_sql('merge_result', conn, if_exists='replace', index=False)
    print("DataFrame успешно выгружен в PostgreSQL!")
except Exception as e:
    print(f"Ошибка выполнения запроса: {e}")

# Закрытие подключения
finally:
    if conn:
        conn.close()
        print("Подключение закрыто")

Подключение установлено
DataFrame успешно выгружен в PostgreSQL!
Подключение закрыто